### ISSUE TITLE
Does not works

### ISSUE THREAD

**Issue by n4skx** [LittleDyingDuck/BinaryNinja-RichPrecense#2]
#### When i "hand install" this plugin it just not works. I already tested creating the connection by my on and works great:
![image](https://github.com/LittleDyingDuck/BinaryNinja-RichPrecense/assets/117673364/35b25d69-6ac6-4321-be39-6200f576cc84)

#### Working as expected:
![image](https://github.com/LittleDyingDuck/BinaryNinja-RichPrecense/assets/117673364/7449cc77-8fd5-42c0-9c24-bdfbb22bd229)

#### Is this a problem with binary ninja itself (like, any updated or api change)?

**Comment by LittleDyingDuck** [comment]
I couldn't be sure and I'm not able to test this any time soon due to some technical difficulties. If you're able to, could you try giving any possible error messages that appear in the binja console? Try both locally installed plugin & the one from the plugin manager built-in to binja

**Comment by n4skx** [comment]
Oh, i already patched it! Seems like the sessions was being reset if the bin ninja was not 'active' (windows) and if the binary ninja starts in background it not works, thanks for the response!
